/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MCO364_Templates;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple unit test for the 'MCO364_Templates.greeting' plugin.
 */
public class MCO364_TemplatesPluginTest {
    @Test public void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("MCO364_Templates.greeting");

        // Verify the result
        assertNotNull(project.getTasks().findByName("greeting"));
    }
}
